apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gatewayclass.yaml
  - gateway.yaml
  - lb-config.yaml
  - routes.yaml

commonAnnotations:
  argocd.argoproj.io/sync-wave: "20"
