#apiVersion: dataprotection.kubeblocks.io/v1alpha1
#kind: BackupSchedule
#metadata:
#  name: qdrant-backup-schedule
#  namespace: rag-platform
#spec:
#  backupPolicyName: qdrant-vector-db-qdrant-backup-policy
#  schedules:
#    - cronExpression: "0 2 * * *"
#      backupMethod: datafile
#      retentionPeriod: 10d
