apiVersion: apps/v1
kind: Deployment
metadata:
  name: tei-embeddings
  labels:
    app: tei-embeddings
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tei-embeddings
  template:
    metadata:
      labels:
        app: tei-embeddings
    spec:
      nodeSelector:
        karpenter.sh/nodepool: apps-serving
        kubernetes.io/arch: amd64
      tolerations:
      - key: role
        operator: Equal
        value: serving
        effect: NoSchedule
      containers:
      - name: tei-embeddings
        image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.5
        resources:
          requests:
            cpu: 1000m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 2Gi
        args: ["--model-id", "BAAI/bge-small-en-v1.5"]
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: tei-cache
          mountPath: /data
      volumes:
      - name: tei-cache
        emptyDir: {}
