apiVersion: apps/v1
kind: Deployment
metadata:
  name: tei-embeddings
  labels:
    app: tei-embeddings
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tei-embeddings
  template:
    metadata:
      labels:
        app: tei-embeddings
    spec:
      nodeSelector:
        karpenter.sh/nodepool: apps-serving
        kubernetes.io/arch: amd64 # ghcr.io/huggingface/text-embeddings-inference has no arm64 manifest
      tolerations:
      - key: role
        operator: Equal
        value: serving
        effect: NoSchedule
      containers:
      - name: tei-embeddings
        image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.6
        env:
        - name: HF_ENDPOINT
          value: "https://huggingface.co"
        - name: HF_HUB_DISABLE_PROXY
          value: "true"
        resources:
          requests:
            cpu: 3000m
            memory: 768Mi
          limits:
            cpu: 4000m
            memory: 1Gi
        args: ["--model-id", "BAAI/bge-small-en-v1.5", "--port", "8080"]
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: tei-cache
          mountPath: /data
      volumes:
      - name: tei-cache
        emptyDir: {}
