apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rag-platform

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: tei-config
    options:
      disableNameSuffixHash: true
    literals:
      - TEI_HOST=tei-embeddings.rag-platform.svc.cluster.local
      - TEI_PORT=80
