apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: tei-embeddings-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tei-embeddings
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
      metricName: tei_avg_cpu
      query: avg(rate(container_cpu_usage_seconds_total{namespace="rag-platform", pod=~"tei-embeddings-.*", container="tei-embeddings"}[2m])) or vector(0)
      threshold: "1.5"
