apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: qdrant
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: 'qdrant-platform'
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "11"
    spec:
      project: default
      sources:
        - repoURL: 'https://github.com/maksimillian1/simple-rag.git'
          targetRevision: SR-infra-prod-setup
          path: deploy/k8s/platform/qdrant/crds
        - repoURL: 'https://apecloud.github.io/helm-charts'
          chart: kubeblocks
          targetRevision: 1.0.2
          helm:
            releaseName: kubeblocks
        - repoURL: 'https://apecloud.github.io/helm-charts'
          chart: qdrant
          targetRevision: '*'
          helm:
            releaseName: qdrant
        - repoURL: 'https://github.com/maksimillian1/simple-rag.git'
          targetRevision: SR-infra-prod-setup
          path: deploy/k8s/platform/qdrant/manifests
      destination:
        server: '{{server}}'
        namespace: kb-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
