apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rag-platform

resources:
  - kubeblocks-cluster.yaml
  - kubeblocks-backup-repo.yaml
  - kubeblocks-backup-policy.yaml

configMapGenerator:
  - name: qdrant-config
    options:
      disableNameSuffixHash: true
    literals:
      - QDRANT_HOST=qdrant.rag-platform.svc.cluster.local
      - QDRANT_GRPC_PORT=6334
      - QDRANT_HTTP_PORT=6333
      - COLLECTION_NAME=demo_collection
