apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rag-platform

resources:
  - kubeblocks-cluster.yaml
  - kubeblocks-backup-repo.yaml
  - kubeblocks-backup-policy.yaml

components:
  - component
