apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rag-jobs

resources:
  - scaledjob.yaml
  - network-policy.yaml

components:
  - ../../platform/qdrant/component
  - ../../platform/tei-embeddings/component
