apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: indexer
spec:
  jobTargetRef:
    template:
      metadata:
        labels:
          app: indexer
      spec:
        serviceAccountName: indexer-sa
        terminationGracePeriodSeconds: 120
        nodeSelector:
          karpenter.sh/nodepool: apps-compute
        tolerations:
        - key: "karpenter.sh/capacity-type"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
        containers:
        - name: indexer
          image: ghcr.io/maksimillian1/simple-rag/indexer:latest
          env:
          - name: AWS_SQS_STAGE_2_URL
            valueFrom:
              configMapKeyRef:
                name: sqs-config
                key: AWS_SQS_STAGE_2_URL
          - name: COLLECTION_NAME
            valueFrom:
              configMapKeyRef:
                name: qdrant-config
                key: COLLECTION_NAME
          - name: INDEXER_QDRANT_HOST
            valueFrom:
              configMapKeyRef:
                name: qdrant-config
                key: QDRANT_HOST
          - name: INDEXER_QDRANT_PORT
            valueFrom:
              configMapKeyRef:
                name: qdrant-config
                key: QDRANT_GRPC_PORT
          - name: TEI_HOST
            valueFrom:
              configMapKeyRef:
                name: tei-config
                key: TEI_HOST
          - name: TEI_PORT
            valueFrom:
              configMapKeyRef:
                name: tei-config
                key: TEI_PORT
          - name: INDEXER_EMBEDDING_MODEL_TEI_URL
            value: "http://$(TEI_HOST):$(TEI_PORT)"
        restartPolicy: Never
  pollingInterval: 15
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  maxReplicaCount: 100
  triggers:
  - type: aws-sqs-queue
    metadata:
      queueURLFromEnv: AWS_SQS_STAGE_2_URL
      awsRegion: "eu-central-1"
      queueLength: "5"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: indexer-sa
