apiVersion: gateway.networking.k8s.io/v1
kind: TCPRoute
metadata:
  name: api-route
  namespace: rag-api
spec:
  parentRefs:
    - name: cilium-gateway
      namespace: rag-platform
  rules:
    - backendRefs:
        - name: api
          port: 80
