apiVersion: v1
kind: Secret
metadata:
  name: git-repository-creds
  namespace: argocd
  labels:
    "argocd.argoproj.io/secret-type": "repository"
type: Opaque
stringData:
  type: git
  url: "https://github.com/maksimillian1/simple-rag.git"
  username: "argo"
  password: {{ .Values.githubToken | quote }}
