{{- range .Values.componentNamespaces }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sqs-config
  namespace: {{ . }}
data:
  AWS_SQS_STAGE_1_URL: {{ $.Values.sqsChunkerUrl | quote }}
  AWS_SQS_STAGE_2_URL: {{ $.Values.sqsIndexerUrl | quote }}
{{- end }}
