apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rag-api

resources:
  - deployment.yaml
  - network-policy.yaml

components:
  - ../../../platform/qdrant/component
  - ../../../platform/tei-embeddings/component
