apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: api-netpol
spec:
  endpointSelector:
    matchLabels:
      app: api
  ingress:
  - fromEntities:
    - world
    - cluster
    toPorts:
    - ports:
      - port: "8080"
        protocol: TCP
  egress:
  - toEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: kube-system
        k8s-app: kube-dns
    toPorts:
    - ports:
      - port: "53"
        protocol: ANY
  - toEndpoints:
    - matchLabels:
        apps.kubeblocks.io/component-name: qdrant
        io.kubernetes.pod.namespace: rag-platform
    toPorts:
    - ports:
      - port: "6333"
        protocol: TCP
      - port: "6334"
        protocol: TCP
  - toEndpoints:
    - matchLabels:
        app: tei-embeddings
        io.kubernetes.pod.namespace: rag-platform
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP
  - toFQDNs:
    - matchPattern: "bedrock-runtime.*.amazonaws.com"
    toPorts:
    - ports:
      - port: "443"
        protocol: TCP
