apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: api-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api
  minReplicaCount: 2
  maxReplicaCount: 10
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
      metricName: api_avg_cpu
      metricType: AverageValue
      query: sum(rate(container_cpu_usage_seconds_total{namespace="rag-api", pod=~"api-.*", container="api"}[2m])) or vector(0)
      threshold: "0.2"
