apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  sources:
    - repoURL: 'https://grafana.github.io/helm-charts'
      chart: loki-stack
      targetRevision: 2.10.2
      helm:
        releaseName: monitoring
        valueFiles:
        - $values/deploy/k8s/platform/monitoring/values/loki.yaml
    - repoURL: 'https://github.com/maksimillian1/simple-rag.git'
      targetRevision: SR-system-configuration-for-report
      ref: values
