apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  sources:
    - repoURL: 'https://prometheus-community.github.io/helm-charts'
      chart: kube-prometheus-stack
      targetRevision: 61.3.0
      helm:
        releaseName: monitoring
        valueFiles:
        - $values/deploy/k8s/platform/monitoring/values/prometheus.yaml
    - repoURL: 'https://github.com/maksimillian1/simple-rag.git'
      targetRevision: SR-system-configuration-for-report
      ref: values
