apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
configMapGenerator:
  - name: tei-config
    literals:
      - TEI_HOST=tei-embeddings.rag-platform.svc.cluster.local
      - TEI_PORT="80"
