loki:
  nodeSelector:
    tier: database
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "database"
      effect: "NoSchedule"
  persistence:
    enabled: true
    storageClassName: gp3
    size: 10Gi

promtail:
  # Promtail runs as DaemonSet on all nodes, so we tolerate all taints
  tolerations:
    - operator: Exists
      effect: NoSchedule
    - operator: Exists
      effect: NoExecute
