prometheus:
  prometheusSpec:
    retention: 3d
    retentionSize: "7GiB"

    nodeSelector:
      tier: core-on-demand
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

grafana:
  nodeSelector:
    tier: core-on-demand
  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s:%(http_port)s/monitor/"
      serve_from_sub_path: true
  additionalDataSources:
    - name: Prometheus
      type: prometheus
      uid: prometheus
      access: proxy
      url: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
      isDefault: true
      jsonData:
        timeInterval: 30s
    - name: Loki
      type: loki
      uid: loki
      access: proxy
      url: http://loki.monitoring.svc.cluster.local:3100
      jsonData:
        maxLines: 1000

alertmanager:
  alertmanagerSpec:
    nodeSelector:
      tier: core-on-demand

kubeStateMetrics:
  nodeSelector:
    tier: core-on-demand

prometheusOperator:
  nodeSelector:
    tier: core-on-demand
  admissionWebhooks:
    namespace: monitoring
    patch:
      nodeSelector:
        tier: core-on-demand
